name: {{ cookiecutter.project_name }}_checks
on: workflow_call
jobs:
    precommit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: "3.13.0"
                  cache: "pip"
            - uses: pre-commit/action@v3.0.1
    unittests:
        needs: precommit
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:16
                env:
                    POSTGRES_PASSWORD: password
                ports: ["5432:5432"]
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        steps:
            - uses: actions/checkout@v4
            - uses: astral-sh/setup-uv@v3
              with:
                version: "0.4"
                enable-cache: true
                cache-dependency-glob: |
                    **/uv.lock
                    **/pyproject.toml
            - run: uv python install 3.13.0
            - run: uv lock
            - run: uv sync --frozen --all-extras --no-install-project
            - run: uv run pyright
            - run: uv run python ./manage.py validate_templates
            - run: uv run pytest
